[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiscreteChoiceModels = "c2e53169-916a-425c-bc99-aa016d67d968"
IndexedTables = "6deec6e2-d858-57c5-ab9b-e6ca5bd20e43"
JuliaDB = "a93385a2-3734-596a-9a66-3cfbb77141e6"
JuliaDBMeta = "2c06ca41-a429-545c-b8f0-5ca7dd64ba19"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
